# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYwFCUgfYXA_jVQuKFbvbQRlRujm41GQ
"""

import torch.nn as nn

class BayesianMLP(nn.Module):
    def __init__(self):
        super(BayesianMLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(385, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, 1)  # Binary classification (sigmoid output)
        )

    def forward(self, x):
        return self.net(x)