# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reB0WN3N91RraLJP4AfLXO9ZRePopm8b
"""

import torch.nn as nn

class BayesianMLP(nn.Module):
    def __init__(self):
        super(BayesianMLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(3 * 224 * 224, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(256, 2)
        )

    def forward(self, x):
        x = x.view(x.size(0), -1)  # flatten image
        return self.net(x)