# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLIt_7lHFl45ZNrogBms4Zpq76Sl4ECz
"""

import torch.nn as nn
import torch.nn.functional as F

class BayesianMLP(nn.Module):
    def __init__(self):
        super(BayesianMLP, self).__init__()
        self.fc1 = nn.Linear(3 * 224 * 224, 512)
        self.fc2 = nn.Linear(512, 2)

    def forward(self, x):
        x = x.view(x.size(0), -1)  # flatten
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x